import { FareModel } from './fare.model';

export class TravelSolutionModel {
  TravelSolId: number;
  Changes: number;
  DepartureTime: string;
  DepartureDate: string;
  ArrivalTime: string;
  Duration: string;
  DurationMinute: number;
  SingleFare:number;
  ReturnFare:number;
  IsSaleable:boolean;
  IsSingleSaleable:boolean;
  IsReturnSaleable:boolean;
  SaleableMessage:string;
  Currency:string;
  FareList: FareModel[];
  ReturnFareList: FareModel[];
  TicketDescription:string;
  TicketRestriction:string;
  NewFareList: FareModel[];
  NewReturnFareList: FareModel[];
  Operator:string;
  SaleCompany:string;
  IsDelayed:boolean;
  IsCancelled:boolean;
  DarwinDepartureTime:string;
  DarwinArrivalTime:string;
  OperatorChange:number;
  IsAlreadyDepartured:boolean;
  IsSoldOutService: boolean;
  SoldOutMessage: string;
  IsOutwardPromoAvailable: boolean;
  IsReturnPromoAvailable: boolean;
  IsStandardFare: boolean;
  IsStandardPremiumFare: boolean;
  IsFirstClassFare: boolean;
  IsRetStandardFare: boolean;
  IsRetStandardPremiumFare: boolean;
  IsRetFirstClassFare: boolean;
  ArrivalDate: string;
  Brand: string;
  CallingPointName: string;
  IsSeatavailable:boolean;
  IsTrainClosed:boolean;
  IsRetTrainClosed:boolean;
  IsFOSTrainClosed:boolean;
  IsSOSTrainClosed:boolean;
  IsBusReplacement:boolean
  IsDarwinNews:boolean;
  TravelSolutionCache: string;
  ReservationID: string;
  IsCheapest: boolean;
  IsOutwardGroupSaveAvailable: boolean;
  IsReturnGroupSaveAvailable: boolean;
  IsRailSale : boolean
  OpenReturnExpiryDate?: string;
  }

  export class JourneySummaryModel {
    RailCards: string;
    SingleTime: string;
    SingleDuration: string;
    SingleChanges: number;
    SingleTicketType: string;
    SinglePrice: number;
    OldReturnPrice: number;
    OldOutwardPrice: number;
    SingleCurrency:string;
    SingleOperator:string;
    SingleOperatorChange:number;
    SingleSaleCompany:string;
    SingleTicketDescription:string;
    SingleSelectedFare: FareModel;
    SingleSearchCache: string;
    SingleRouteModel: any;
    ReturnTime: string;
    ReturnDuration: string;
    ReturnChanges: number;
    ReturnTicketType: string;
    ReturnPrice: number;
    ReturnCurrency:string;
    ReturnOperator:string;
    ReturnOperatorChange:number;
    ReturnSaleCompany:string;
    ReturnTicketDescription:string;
    ReturnSelectedFare: FareModel;
    ReturnSearchCache: string;
    ReturnRouteModel: any;
    IsSingleFareSelected: boolean;
    OutwardPlusbus: boolean;
    ReturnPlusbus: boolean;
    OutwardBicycleReservation: boolean;
    ReturnBicycleReservation: boolean;
    OutwardLondonTravelcard: boolean;
    ReturnLondonTravelcard: boolean;
    MultiOutwardPlusbus: boolean;
    MultiReturnPlusbus: boolean;
    IsPromo: boolean;
    SingleChoosedTravelSolution: TravelSolutionModel;
    ReturnChoosedTravelSolution: TravelSolutionModel;
    activeTab: number;
    TravelId: number;
    TravelSolutionId: number;
    DeliveryMode: string;
    ReopenCache: string;
    outwardDate: string;
    returnDate: string;
    ChoosedTrainleg: string;
    IsCOJWithTravelExtra: boolean;
  }
