
export class EnhancedDataLayerChangeSeatItemType {
  action: string | undefined;
  feature: string | undefined;
  coach: string | undefined;
  seat_number: string | undefined;
  departure_date: string | undefined;
  return_date: string | undefined;
  journey_duration: string | undefined;
  origin: string | undefined;
  destination: string | undefined;
  ticket_class: string | undefined;
  ticket_type: string | undefined;
  ticket_route_code: string | undefined;
  ticket_type_code: string | undefined;
  type: string | undefined;
  single_or_return: string | undefined;
  number_of_changes: string | undefined;
  additional_information: string | undefined;
  days_in_advance: number | undefined;
  railcard_code: string | undefined;
  railcard_used: boolean | undefined;
  adult_pax: number | undefined;
  child_pax: number | undefined;
  total_pax: number | undefined;
  price: number | undefined;
  message: string | undefined;
  item_name: string | undefined;
  item_id: string | undefined;
  item_brand: string | undefined;
  item_category: string | undefined;
  item_category2: string | undefined;
  item_category3: string | undefined;
  item_category5: string | undefined;
  item_category4: string | undefined;
  item_variant: string | undefined;
  item_list_id: number | undefined;
  index: number | undefined;
  column_index: number | undefined;
  start_date: string | undefined;
  end_date: string | undefined;
  operator: string | undefined;
  duration: string | undefined;
  status: string | undefined;
  seat_direction: string | undefined;
  seat_position: string | undefined;
  seat_preferences: string | undefined;
  start_time: string | undefined = undefined;
  end_time: string | undefined = undefined;
  available_classes: string | undefined = undefined;
  item_list_name: string | undefined = undefined;
}