using System.Text;
using Q3.ModernizationEngine.Core.Abstractions;
using Q3.ModernizationEngine.Shared.Models;

namespace Q3.ModernizationEngine.Core.Execution;

public sealed class DeterministicModuleContentGenerator : IModuleContentGenerator
{
    public Task<ModuleExecutionResult> GenerateAsync(
        ModernizationRequest request,
        ModuleMigrationPlan plan,
        WorkspacePlacement placement,
        IModernizationProgressReporter progress,
        CancellationToken cancellationToken = default)
    {
        progress.Detail($"Using deterministic generator for {plan.UnitName}.");
        var artifacts = new List<GeneratedArtifact>();
        var warnings = new List<string>();

        Directory.CreateDirectory(placement.WorkspaceFolder);

        if (plan.Track == "Blazor" && IncludesBlazor(plan.TargetMode))
        {
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}.razor", "blazor-page", BuildBlazorPage(plan)));
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}ViewModel.cs", "blazor-viewmodel", BuildViewModel(plan)));
        }

        if (IncludesApi(plan.TargetMode))
        {
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}Endpoint.cs", "api-endpoint", BuildApiEndpoint(plan)));
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}Contracts.cs", "api-contracts", BuildApiContracts(plan)));
        }

        if (plan.Track == "BusinessLogic")
        {
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}Service.cs", "business-service", BuildBusinessService(plan)));
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}ServiceContract.cs", "business-contract", BuildBusinessContract(plan)));
        }

        if (plan.SqlArtifacts.Count > 0)
        {
            artifacts.Add(WriteArtifact(placement, $"{Sanitize(plan.UnitName)}.sql", "sql-script", BuildSqlTemplate(plan)));
            warnings.Add("SQL-related migration work was detected. Review generated SQL placeholder before execution.");
        }

        if (plan.ManualReviewReasons.Count > 0)
        {
            warnings.AddRange(plan.ManualReviewReasons);
        }

        return Task.FromResult(new ModuleExecutionResult
        {
            UnitId = plan.UnitId,
            UnitName = plan.UnitName,
            Track = plan.Track,
            ExecutorMode = request.Ai.UseAi ? "generic-execution-fallback" : "deterministic",
            WorkspaceFolder = placement.WorkspaceFolder,
            GeneratedArtifacts = artifacts,
            Warnings = warnings
        });
    }

    private static GeneratedArtifact WriteArtifact(WorkspacePlacement placement, string fileName, string kind, string content)
    {
        var path = Path.Combine(placement.WorkspaceFolder, fileName);
        File.WriteAllText(path, content, Encoding.UTF8);
        return new GeneratedArtifact
        {
            RelativePath = Path.GetRelativePath(placement.WorkspaceFolder, path).Replace(Path.DirectorySeparatorChar, '/'),
            Kind = kind,
            Summary = $"Generated {kind} scaffold in {placement.Track} track."
        };
    }

    private static string BuildBlazorPage(ModuleMigrationPlan plan) => $$"""
@page "/{{Slug(plan.UnitName)}}"

<PageTitle>{{plan.UnitName}}</PageTitle>

<h3>{{plan.UnitName}}</h3>

<p>This scaffold was generated by the migration master for the {{plan.Track}} track.</p>

<ul>
@foreach (var step in MigrationSteps)
{
    <li>@step</li>
}
</ul>

@code {
    private static readonly string[] MigrationSteps = new[]
    {
{{JoinLines(plan.Steps.Select(s => $"        \"{Escape(s)}\","))}}
    };
}
""";

    private static string BuildViewModel(ModuleMigrationPlan plan) => $$"""
namespace Generated.Blazor;

public sealed class {{Sanitize(plan.UnitName)}}ViewModel
{
    public string Title { get; } = "{{Escape(plan.UnitName)}}";
    public string Summary { get; } = "{{Escape(plan.Summary)}}";
}
""";

    private static string BuildApiEndpoint(ModuleMigrationPlan plan) => $$"""
namespace Generated.Api;

public static class {{Sanitize(plan.UnitName)}}Endpoint
{
    public static string Route => "/api/{{Slug(plan.UnitName)}}";
}
""";

    private static string BuildApiContracts(ModuleMigrationPlan plan) => $$"""
namespace Generated.Api;

public sealed record {{Sanitize(plan.UnitName)}}Request(string CorrelationId);

public sealed record {{Sanitize(plan.UnitName)}}Response(string Message);
""";

    private static string BuildBusinessService(ModuleMigrationPlan plan) => $$"""
namespace Generated.BusinessLogic;

public sealed class {{Sanitize(plan.UnitName)}}Service : I{{Sanitize(plan.UnitName)}}Service
{
    public string Describe() => "{{Escape(plan.Summary)}}";
}
""";

    private static string BuildBusinessContract(ModuleMigrationPlan plan) => $$"""
namespace Generated.BusinessLogic;

public interface I{{Sanitize(plan.UnitName)}}Service
{
    string Describe();
}
""";

    private static string BuildSqlTemplate(ModuleMigrationPlan plan) => $$"""
-- SQL migration placeholder for {{plan.UnitName}}
-- Review and replace with real extraction or migration script.

{{JoinLines(plan.SqlArtifacts.Select(s => $"-- {Escape(s)}"))}}
""";

    private static string Sanitize(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var cleaned = new string(name.Where(ch => !invalid.Contains(ch)).ToArray());
        cleaned = cleaned.Replace(" ", "", StringComparison.Ordinal);
        return string.IsNullOrWhiteSpace(cleaned) ? "GeneratedModule" : cleaned;
    }

    private static string Slug(string name) =>
        string.Join("-", name.Split([' ', '_', '-'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)).ToLowerInvariant();

    private static bool IncludesBlazor(string targetMode) =>
        targetMode is "blazor-only" or "blazor-and-api";

    private static bool IncludesApi(string targetMode) =>
        targetMode is "api-only" or "blazor-and-api";

    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    private static string JoinLines(IEnumerable<string> lines) => string.Join(Environment.NewLine, lines);
}
