import { CojEvaluateTravelRequest, EvaluateTravelRequest } from '../models/journey-extras/evaluate-request.model';
import { DeliveryMode } from '../models/delivery-modes/delivery-modes.model';
import { COJSearchRequestModel, SearchRequestModel } from '../models/mixing-deck/search-request.model';
import { CojReviewBuyResponse, RailCardPriceList, ReservationSeat, ReviewBuyResponse } from '../models/review-buy/review-buy-model';
import { FareBreakdownModel } from '../models/mixing-deck/fare-breakdown.model';
import { PaymentResponse } from '../models/payment-details/payment-response.model';
import { ValidatePaymentResponse } from '../models/payment-details/validate-payment-response.model';
import { LocationMasterData } from '../models/master/location-master.model';
import { JourneyExtrasResponse } from '../models/journey-extras/journey-extras-response.model';
import { CreateReservationRequest } from '../models/journey-extras/reservation.model';
import { ChangeSeatRequestDto, EvaluateRequestDto, JourneyDetails, ReserveSeatRequestDto, SearchSimilarForDateResponseDto } from '../models/account/my-bookings.model';
import { JourneySummaryModel } from '../models/mixing-deck/travel-solution.model';
import { SeatPickerResponseDto } from '../models/review-buy/seat-picker-model';
import { EnhancedReviewBuyAndDeliveryResponse } from '../models/enhanced-review-buy-and-delivery/enhanced-review-buy-delivery.model';
import { EnhancedGetDeliveryAndBasketJourneyRequest } from '../models/enhanced-review-buy-and-delivery/enhanced-get-delivery-and-basket-journey-request';

export class SharedServiceCache {
  addReturnTabIndex: number = 0;
  evaluateRequest: EvaluateTravelRequest = new EvaluateTravelRequest();
  fare: number = 0;
  fareReturn: number = 0;
  totalFare:number = 0;
  isReturnCase:boolean = false;
  isSingleReturnCase:boolean = false;
  deliveryModes:DeliveryMode = new DeliveryMode();
  searchRequest: SearchRequestModel = new SearchRequestModel();
  CojSearchRequest: COJSearchRequestModel = new COJSearchRequestModel();
  upgradeSearchRequest: COJSearchRequestModel = new COJSearchRequestModel();
  CojReviewBuyRequest: CojEvaluateTravelRequest = new CojEvaluateTravelRequest();
  upgradeReviewBuyRequest: CojEvaluateTravelRequest = new CojEvaluateTravelRequest();
  isLogin:boolean = false;
  mixingDeckUrl: string = "";
  isAmendSearchOpen:boolean = false;
  customerFirstName: string = "";
  customerLastName: string = "";
  reviewBuyCache: string = "";
  previousCache: string = "";
  totalPriceToPayReviewBuy = null;
  basketCount:number = 0;
  fareBreakDownTotalFare:number = 0;
  ReservationCache: string = "";
  isReturnLoaderCase:boolean = false;
  fareBreakDownTotalDiscount:number = 0;
  isAmendFresh: boolean = false;
  journeyExtrasResponseShared: JourneyExtrasResponse = new JourneyExtrasResponse();
  reviewBuyResponse:ReviewBuyResponse = new ReviewBuyResponse();
  CojReviewBuyResponseDto:CojReviewBuyResponse = new CojReviewBuyResponse();
  validatePaymentResponse: ValidatePaymentResponse = new ValidatePaymentResponse();
  fareBreakdownModelData: FareBreakdownModel[] = new Array<FareBreakdownModel>();
  locationMasterData: LocationMasterData[] = new Array<LocationMasterData>();
  paymentResponse: PaymentResponse = new PaymentResponse();
  createReservationRequest: CreateReservationRequest = new CreateReservationRequest();
  IsViewMoreClick: boolean=false;
  IsViewMoreClickSingleReturn: boolean=false;
  journey: JourneyDetails;
  registrationCustomerEmail: string;
  registrationCustomerPassword: string;
  registrationIsLoginFromJE: boolean;
  registrationIsLoginFromSeason: boolean;
  registrationReturnUrl: string;
  isNreBasket: boolean;
  firstTravelSolDepartureTime:string;
  firstTravelSolDepartureTimeAmend:string;
  secondTravelSolDepartureTime:string;
  secondTravelSolDepartureTimeAmend:string;
  journeySummaryModel: JourneySummaryModel;
  COJjourneySummaryModel: JourneySummaryModel;
  upgradeOutwardPrice: number;
  upgradeReturnPrice: number;
  seatPickerResponseAmend: SeatPickerResponseDto;
  reserveSeatRequest: ReserveSeatRequestDto;
  changeSeatRequest: ChangeSeatRequestDto;
  searchSimilarResponse: SearchSimilarForDateResponseDto;
  selectedAmendLeg: ReservationSeat;
  reserveSeatRequestDate: Date;
  IsReturnTypeTicket: boolean;
  IsRetReservationAvailable: boolean;
  IsOutReservationAvailable: boolean;
  amendReviewBuyData: CojReviewBuyResponse;
  amendReviewBuyEvaluateRequest: EvaluateRequestDto;
  reviewBuyJourneyTimeStampArr: any[];
  noOfAdultAmend: number;
  noOfChildAmend: number;
  IsPartialReturnTypeTicket: boolean;
  //Added a property so on return from travel extra editQtt input dates do not change
  editQttDepartureTimeStart : string;
  editQttReturnTimeStart : string;
  railCardPriceList: RailCardPriceList[];
  LatestJourneyCache: string;
  postSaleReviewBuyCache: string;
  selectedJourneyDataForQuickBuyOrContiue: any[];
  enhancedReviewBuyResponse:EnhancedReviewBuyAndDeliveryResponse = new EnhancedReviewBuyAndDeliveryResponse();
  enhancedGetDeliveryAndBasketJourneyRequest: EnhancedGetDeliveryAndBasketJourneyRequest = new EnhancedGetDeliveryAndBasketJourneyRequest();
}
